import {
  Activity,
  BarChart3,
  BookOpen,
  CalendarDays,
  CalendarClock,
  ClipboardList,
  GraduationCap,
  Clock,
  LayoutDashboard,
  Layers,
  ListChecks,
  NotebookText,
  Timer,
} from "lucide-react"

export const NAV_ITEMS = [
  { href: "/dashboard", label: "Dashboard", icon: LayoutDashboard },
  { href: "/courses", label: "Courses", icon: BookOpen },
  { href: "/timetable", label: "Classes", icon: CalendarClock },
  { href: "/assignments", label: "Assignments", icon: ClipboardList },
  { href: "/exams", label: "Exams", icon: GraduationCap },
  { href: "/calendar", label: "Calendar", icon: CalendarDays },
  { href: "/notes", label: "Notes", icon: NotebookText },
  { href: "/quizzes", label: "Quizzes", icon: ListChecks },
  { href: "/flashcards", label: "Flashcards", icon: Layers },
  { href: "/pomodoro", label: "Pomodoro", icon: Timer },
  { href: "/study-plan", label: "Study Plan", icon: Clock },
  { href: "/study-analytics", label: "Study Analytics", icon: Activity },
  { href: "/gpa-tracker", label: "GPA Tracker", icon: BarChart3 },
] as const
